on:
  workflow_call:
    inputs:
      bu:
        required: true
        type: string
        description: 'business unit name'
      environment:
        required: true
        type: string
      service_name:
        required: true
        type: string
        description: 'service name, also will be used as ecr repo name'
      aws_ssm_region:
        required: true
        type: string
      config_path:
        required: false
        type: string
        default: 'iac/service.config.yml'

name: Deployment Pipeline
jobs:
  config: 
    name: Generate Config 
    runs-on: [ self-hosted, eks-runner ]
    outputs:
      environment: ${{ steps.config.outputs.environment }}
      eks_cluster: ${{ steps.config.outputs.eks_cluster }}
      namespace: ${{ steps.config.outputs.namespace }}
      build_role_arn: ${{ steps.config.outputs.build_role_arn }}
      deploy_role_arn: ${{ steps.config.outputs.deploy_role_arn }}
      aws_region: ${{ steps.config.outputs.aws_region }}
    steps:
      - name: Checkout Generate Config Action Repo
        uses: actions/checkout@v2
        with:
          repository: qoala-engineering/generate-config-action
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/generate-config-action
      
      - name: Generate Config
        uses: ./.github/actions/generate-config-action
        id: config
        with:
          bu: ${{ inputs.bu }}
          environment: ${{ inputs.environment }}

  build:
    name: Build Image
    needs: config
    runs-on: [ self-hosted, eks-runner ]
    outputs:
      image_registry: ${{ steps.publish_image.outputs.image_registry }}
      image_meta: sha-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout ECR Publish GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: qoala-engineering/ecr-publish-action
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/ecr-publish-action

      - name: Build and Push Image
        uses: ./.github/actions/ecr-publish-action
        id: publish_image
        with:
          aws-region: ${{ needs.config.outputs.aws_region }}
          ecr_name: ${{ inputs.service_name }}
          role-to-assume: ${{ needs.config.outputs.build_role_arn }}
          ecr_cache_tag: latest-${{ needs.config.outputs.environment }}
          build_args: |
            GITHUB_TOKEN=${{ secrets.GIT_HUB_TOKEN }}
          custom_tags: |
            latest-${{ needs.config.outputs.environment }}
            sha-${{ github.sha }}

  deploy:
    name: Deploy Service
    needs: build
    runs-on: [self-hosted, eks-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: qoala-engineering/setup-eks-helm-action
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/setup-eks-helm-action

      - uses: ./.github/actions/setup-eks-helm-action
        with:
          aws-region: ${{ needs.config.outputs.aws_region }}
          role-to-assume: ${{ needs.config.outputs.deploy_role_arn }}
          github-token: ${{ secrets.GIT_HUB_TOKEN }}
          cluster-name: ${{ needs.config.outputs.eks_cluster }}
      
      - name: Checkout SSM Injection
        uses: actions/checkout@v2
        with:
          repository: qoala-engineering/helm-values-ssm-injection
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/helm-values-ssm-injection

      - name: SSM Injection
        id: values
        uses: ./.github/actions/helm-values-ssm-injection
        with:
          image: ${{ needs.build.outputs.image_registry }}/${{ inputs.service_name }}:${{ needs.build.outputs.image_tag }}
          environment: ${{ needs.config.outputs.environment }}
          configPath: ${{ inputs.config_path }}
 
      - name: Deploy service
        shell: bash
        run: |
          helm upgrade --install --atomic --wait --namespace ${{ needs.config.outputs.namespace }} --create-namespace ${{ inputs.service_name }} .charts/charts/service -f ${{ steps.values.outputs.values }}
